# Generated by Django 3.2.3 on 2021-06-08 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=1000)),
                ('Incident_Department', models.CharField(max_length=1000)),
                ('Date_Of_Incident', models.DateField(default=django.utils.timezone.now)),
                ('Time_Of_Incident', models.TimeField()),
                ('Incident_Location', models.CharField(max_length=1000)),
                ('Suspected_Cause', models.CharField(max_length=1000)),
                ('Immediate_Action', models.CharField(max_length=1000)),
                ('Environmental_Incident', models.CharField(max_length=1000)),
                ('Injury_Illness', models.CharField(max_length=1000)),
                ('Property_Damage', models.CharField(max_length=1000)),
                ('Vehicle', models.CharField(max_length=1000)),
                ('Reported_By', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MarkyticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
